export const ResponseMessage = Object.freeze({
  success: 'success',
  noData: 'no data',
  noUser: 'no user',
  tokenRequired: 'token is required',
  tokenInvalid: 'token is invalid',
  passwordIncorrect: 'password is incorrect',
  userExist: `user exist`,
  fail: 'fail',
  conflict: 'conflict',
  noAdmin: 'no admin',
  platformRequired: 'platform is required',
  cannotConnectSns: 'cannot connect sns',
  adminExist: 'admin exist',
  needMoreInfo: 'need more info',
  badRequest: 'bad request',
  forbidden: 'forbidden',
  unauthorized: 'unauthorized',
  internalServerError: 'internal server error',
});